// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextUsageCategory } from "./ContextUsageCategory";
import type { ContextUsageCompleteness } from "./ContextUsageCompleteness";
import type { ContextUsageDetail } from "./ContextUsageDetail";

export type ContextUsageSnapshot = { snapshotId: string, requestSequence: number, generatedAt: number, model: string, modelContextWindow: number | null, autoCompactThreshold: number | null, reservedTokens: number | null, categories: Array<ContextUsageCategory>, mcpToolDetails: Array<ContextUsageDetail>, instructionDetails: Array<ContextUsageDetail>, skillDetails: Array<ContextUsageDetail>, estimatedTotalTokens: number, completeness: ContextUsageCompleteness, requestConfigVersion: number, };
